version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=example

  basketdb:
    container_name: basketdb
    restart: always
    # command: redis-server --save 20 1 --loglevel warning --requirepass example
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1433:1433"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "8080:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"


  catalog.api:
    container_name: catalog.api
    environment:
      - DB_HOST=catalogdb
      - DB_PORT=27017
      - DB_NAME=ProductDb
      - DB_COLLECTION_NAME=Products
    depends_on:
      - catalogdb
    ports:
      - "8001:80"

  basket.api:
    container_name: basket.api
    environment:
      - REDIS_HOST=basketdb
      - REDIS_PORT=6379
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    depends_on:
      - basketdb
    ports:
      - "8002:80"

  discount.api:
    container_name: discount.api
    environment:
      - POSTGRES_HOST=discountdb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - POSTGRES_HOST=discountdb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    depends_on:
      - discountdb
    ports:
      - "8004:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - DB_HOST=orderdb
      - DB_NAME=OrderDb
      - DB_USER_ID=sa
      - DB_PASSWORD=SwN12345678
    depends_on:
      - orderdb
    ports:
      - "8005:80"