version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres
  
  orderdb:
    image: mcr.microsoft.com/mssql/server
    
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  rabbitmq:
    image: rabbitmq:3-management-alpine


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build: 
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build: 
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  
  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: APIGateways/OcelotApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mongo_data:
    name: mongo_data
  portainer_data:
    name: portainer_data
  postgres_data:
    name: postgres_data
  pgadmin_data:
    name: pgadmin_data