version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build: 
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
      - "81"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build: 
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    ports:
      - "82"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  discount.grpc:
    image: ${DOCKER_REGISTRY}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mongo_data:
    name: mongo_data
  portainer_data:
    name: portainer_data
  postgres_data:
    name: postgres_data
  pgadmin_data:
    name: pgadmin_data